"""Initial migration

Revision ID: 486b167d3840
Revises: 
Create Date: 2025-11-15 10:45:12.474475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486b167d3840'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('model_path', sa.String(length=500), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('model_name', 'version', name='unique_model_version')
    )
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_model_status'), ['status'], unique=False)

    op.create_table('certification_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_number')
    )
    op.create_table('permission',
    sa.Column('perm_id', sa.Integer(), nullable=False),
    sa.Column('perm_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('perm_id'),
    sa.UniqueConstraint('perm_name')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_is_available'), ['is_available'], unique=False)

    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('perm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perm_id'], ['permission.perm_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'perm_id')
    )
    op.create_table('training_data',
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('reward', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_model.model_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('data_id')
    )
    with op.batch_alter_table('training_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_data_model_id'), ['model_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_certified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)

    op.create_table('certificate',
    sa.Column('cert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cert_type', sa.String(length=100), nullable=False),
    sa.Column('issued_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('cert_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cert_id'),
    sa.UniqueConstraint('cert_number')
    )
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_user_id'), ['user_id'], unique=False)

    op.create_table('robot',
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('robot_name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('model_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('battery_lvl', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('current_position', sa.JSON(), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('last_maint', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('robot_id')
    )
    with op.batch_alter_table('robot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_robot_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_robot_status'), ['status'], unique=False)

    op.create_table('user_certification_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['certification_module.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id', name='unique_user_module')
    )
    with op.batch_alter_table('user_certification_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_certification_progress_user_id'), ['user_id'], unique=False)

    op.create_table('booking',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('booking_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.robot_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_booking_type'), ['booking_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_user_id'), ['user_id'], unique=False)

    op.create_table('maintenance',
    sa.Column('maint_id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('tech_id', sa.Integer(), nullable=True),
    sa.Column('maint_type', sa.String(length=100), nullable=False),
    sa.Column('schedule_dt', sa.DateTime(), nullable=True),
    sa.Column('completed_dt', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.robot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tech_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('maint_id')
    )
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_robot_id'), ['robot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_tech_id'), ['tech_id'], unique=False)

    op.create_table('mission',
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('ai_model_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('area_coords', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('area_covered', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('waste_collected', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_model.model_id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.robot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mission_id')
    )
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mission_robot_id'), ['robot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mission_status'), ['status'], unique=False)

    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('operation_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('robot_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.mission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.robot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_log_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_robot_id'), ['robot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_status'), ['status'], unique=False)

    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('depth', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ph', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('water_quality', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('camera_data', sa.JSON(), nullable=True),
    sa.Column('lidar_data', sa.JSON(), nullable=True),
    sa.Column('waste_detected', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.mission_id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.robot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_data_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_data_robot_id'), ['robot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_data_timestamp'), ['timestamp'], unique=False)

    op.create_table('waste',
    sa.Column('waste_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('waste_type', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('collected', sa.Boolean(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.mission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('waste_id')
    )
    with op.batch_alter_table('waste', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waste_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waste_waste_type'), ['waste_type'], unique=False)

    op.create_table('ml_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('sensor_data_id', sa.Integer(), nullable=True),
    sa.Column('ai_model_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('velocity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('turn_direction', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('waste_collector_status', sa.String(length=50), nullable=True),
    sa.Column('navigation_mode', sa.String(length=50), nullable=True),
    sa.Column('target_position', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reward_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_model.model_id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.mission_id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.robot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_data_id'], ['sensor_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_decision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_decision_ai_model_id'), ['ai_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_decision_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_decision_robot_id'), ['robot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_decision_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_decision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_decision_timestamp'))
        batch_op.drop_index(batch_op.f('ix_ml_decision_robot_id'))
        batch_op.drop_index(batch_op.f('ix_ml_decision_mission_id'))
        batch_op.drop_index(batch_op.f('ix_ml_decision_ai_model_id'))

    op.drop_table('ml_decision')
    with op.batch_alter_table('waste', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waste_waste_type'))
        batch_op.drop_index(batch_op.f('ix_waste_mission_id'))

    op.drop_table('waste')
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_data_timestamp'))
        batch_op.drop_index(batch_op.f('ix_sensor_data_robot_id'))
        batch_op.drop_index(batch_op.f('ix_sensor_data_mission_id'))

    op.drop_table('sensor_data')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_status'))
        batch_op.drop_index(batch_op.f('ix_payment_booking_id'))

    op.drop_table('payment')
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_operation_log_robot_id'))
        batch_op.drop_index(batch_op.f('ix_operation_log_mission_id'))

    op.drop_table('operation_log')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_booking_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_status'))
        batch_op.drop_index(batch_op.f('ix_mission_robot_id'))
        batch_op.drop_index(batch_op.f('ix_mission_operator_id'))

    op.drop_table('mission')
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_tech_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_status'))
        batch_op.drop_index(batch_op.f('ix_maintenance_robot_id'))

    op.drop_table('maintenance')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_user_id'))
        batch_op.drop_index(batch_op.f('ix_booking_status'))
        batch_op.drop_index(batch_op.f('ix_booking_booking_type'))

    op.drop_table('booking')
    with op.batch_alter_table('user_certification_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_certification_progress_user_id'))

    op.drop_table('user_certification_progress')
    with op.batch_alter_table('robot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_robot_status'))
        batch_op.drop_index(batch_op.f('ix_robot_owner_id'))

    op.drop_table('robot')
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_user_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_status'))

    op.drop_table('certificate')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('training_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_data_model_id'))

    op.drop_table('training_data')
    op.drop_table('role_permission')
    op.drop_table('role')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_is_available'))
        batch_op.drop_index(batch_op.f('ix_product_category'))

    op.drop_table('product')
    op.drop_table('permission')
    op.drop_table('certification_module')
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_model_status'))

    op.drop_table('ai_model')
    # ### end Alembic commands ###
